const { DataTypes } = require("sequelize");

module.exports = model;

function model(sequelize) {
  const attributes = {
    email: { type: DataTypes.STRING},
    empName: { type: DataTypes.TEXT},
    empNameInit: { type: DataTypes.TEXT},
    relEmp: { type: DataTypes.STRING},
    empStatus: { type: DataTypes.STRING},
    policePersonnel: { type: DataTypes.STRING}, //missing
    spouseCertificate: { type: DataTypes.STRING},
    dob: { type: DataTypes.TEXT},
    ranks: { type: DataTypes.STRING}, //missing
    gpfcpsNumber: { type: DataTypes.STRING},
    // ploliceGradeNnumber: { type: DataTypes.STRING},
    stationUnit: { type: DataTypes.STRING},
    workingDistrict: { type: DataTypes.STRING},
    lastDistrict: { type: DataTypes.STRING},
    policeMobilePhone: { type: DataTypes.STRING},
    CandidateNname: { type: DataTypes.STRING},
    CandidateNnameInit: { type: DataTypes.STRING},
    gender: { type: DataTypes.TEXT},
    dobDate: { type: DataTypes.TEXT},
    email1: { type: DataTypes.STRING},
    phone1: { type: DataTypes.STRING},
    address1: { type: DataTypes.TEXT},
    address2: { type: DataTypes.TEXT},
    address3: { type: DataTypes.TEXT},
    CityDistrict: { type: DataTypes.STRING},
    state1: { type: DataTypes.STRING},
    pincode: { type: DataTypes.STRING},
    aadharNumber: { type: DataTypes.STRING},
    myCheckboxes: { type: DataTypes.STRING},
    perference1: { type: DataTypes.TEXT},
    preference2: { type: DataTypes.TEXT},
    preference3: { type: DataTypes.TEXT},
    otherPreferred: { type: DataTypes.STRING},
    workPreference1: { type: DataTypes.STRING},
    workPreference2: { type: DataTypes.STRING},
    workPreference3: { type: DataTypes.STRING},
    skills: { type: DataTypes.STRING},
    candPhoto: { type: DataTypes.STRING},
    resume: { type: DataTypes.STRING},
    Qualification: { type: DataTypes.STRING},
    studied: { type: DataTypes.STRING},
    Board: { type: DataTypes.STRING},
    pass10: { type: DataTypes.TEXT},
    Percentage: { type: DataTypes.STRING},
    Board12: { type: DataTypes.STRING},
    Passing: { type: DataTypes.TEXT},
    Percentage12: { type: DataTypes.STRING},
    course: { type: DataTypes.STRING},
    Passingiti: { type: DataTypes.TEXT},
    Percentageiti: { type: DataTypes.STRING},
    courseDip: { type: DataTypes.STRING},
    PassingDip: { type: DataTypes.TEXT},
    PercentageDip: { type: DataTypes.STRING},
    GraduationDg: { type: DataTypes.STRING},
    Institute: { type: DataTypes.STRING},
    Subject: { type: DataTypes.STRING},
    Passinghigi: { type: DataTypes.TEXT},
    Percentagehigi: { type: DataTypes.STRING},
    Degreename: { type: DataTypes.STRING},
    University: { type: DataTypes.STRING},
    MajorSubject: { type: DataTypes.STRING},
    passedYear: { type: DataTypes.TEXT},
    Percentageunder: { type: DataTypes.STRING},
    Universityphd: { type: DataTypes.STRING},
    Subjectphd: { type: DataTypes.STRING},
    Passingphd: { type: DataTypes.STRING},
    Percentagephd: { type: DataTypes.STRING},
    BoardBelow: { type: DataTypes.STRING},
    below10thpass: { type: DataTypes.STRING},
    belowPercentage: { type: DataTypes.STRING},
    Pursuing: { type: DataTypes.STRING},
    UniversityOther: { type: DataTypes.STRING},
    SubjectOther: { type: DataTypes.STRING},
    detailsdeg: { type: DataTypes.STRING},
    Employment: { type: DataTypes.STRING},
    experience: { type: DataTypes.STRING},
    CompanyName: { type: DataTypes.STRING},
    Designation: { type: DataTypes.STRING},
    Workingplz: { type: DataTypes.STRING},
    fromDate: { type: DataTypes.TEXT},
    toDate: { type: DataTypes.TEXT},
    companyDet: { type: DataTypes.STRING},
    userName: { type: DataTypes.STRING},
  };
  return sequelize.define("job_fair", attributes);
}
